spring.application.name=smartgrid
server.port=8080

smartgrid.mqtt.broker-uri=tcp://localhost:1883
smartgrid.mqtt.server-client-id=smartgrid-server
smartgrid.mqtt.topic-prefix=smartgrid

smartgrid.simulator.interval-ms=5000
